<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container23HBOtY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container23HBOtY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container23HBOtY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container23HBOtY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container23HBOtY\App_KernelDevDebugContainer([
    'container.build_hash' => '23HBOtY',
    'container.build_id' => 'd9a4d082',
    'container.build_time' => 1617125565,
], __DIR__.\DIRECTORY_SEPARATOR.'Container23HBOtY');
