<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuESg7V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuESg7V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuESg7V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuESg7V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXuESg7V\App_KernelDevDebugContainer([
    'container.build_hash' => 'XuESg7V',
    'container.build_id' => '816f7eef',
    'container.build_time' => 1617620645,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuESg7V');
